### PR TITLE
fix: ignore models that extend Jenssegers\Mongodb\Eloquent\Model

### LINKED ISSUE #239: Error on MongoDb models
- Laravel Version: 7.12.0
- PHP Version: 7.4.4
- Blueprint Version: 1.12.0
- Platform: Mac

### Description:
Running blueprint:trace on an existing project which has models that extend Jenssegers\Mongodb\Eloquent provided by "jenssegers/mongodb" package, throws exception.

**ErrorException** 

**call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getDoctrineDriver'**

### Steps To Reproduce:
Run blueprint:trace command on a project that has a models extend Jenssegers\Mongodb\Eloquent

### Workaround
I've added one more check to the TraceCommand's loadModel method.

```php
if ($reflectionClass->isSubclassOf('Jenssegers\Mongodb\Eloquent\Model')) {
    return null;
}
```

### Output
  call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getDoctrineDriver'

  at vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:279
    275▕      * @return mixed
    276▕      */
    277▕     public function __call($method, $parameters)
    278▕     {
  ➜ 279▕         return call_user_func_array([$this->db, $method], $parameters);
    280▕     }
    281▕ }
    282▕

### PR DESCRIPTION
**Pull request by buraksh**
Closes #239

### CODE REVIEW

**Comment by jasonmccreary** [comment]
Thanks for this. Have you verified this resolves the MongoDB error and the trace command runs correctly?

I don't use MongoDB nor have access. So I'm relying on you to verify...

**Comment by buraksh** [comment]
Yes, I have tested it and the trace command runs successfully.

image

**Comment by jasonmccreary** [comment]
Just curious, what does the `trace` output look like (`.blueprint`)?

**Comment by buraksh** [comment]
```yaml
models:
    Models\AccessCode: { tenant_id: 'integer unsigned nullable', venue_id: 'integer unsigned nullable', guest_id: 'integer unsigned nullable', service_profile_id: 'integer unsigned', type: 'boolean unsigned', code: 'string:20', description: 'string nullable', start_date: 'datetime nullable', expiry_date: 'datetime nullable', use_count: 'boolean unsigned default:0', used_at: 'datetime nullable', logout_time: 'datetime nullable', status: 'boolean unsigned', created_by: 'integer unsigned nullable' }
    Models\ActivityLog: { tenant_id: 'integer unsigned', user_id: 'integer unsigned', description: text, ip_address: 'string:45', user_agent: text, created_at: 'datetime default:CURRENT_TIMESTAMP' }
    Models\Advertisement: { tenant_id: 'integer unsigned', title: string, type: 'boolean unsigned default:0', body: 'text nullable', image: 'string nullable', url: 'string nullable', start_date: datetime, end_date: datetime, method: 'boolean unsigned default:1', condition_value: 'smallinteger unsigned nullable', impression_count: 'integer unsigned default:0', click_count: 'integer unsigned default:0', status: 'boolean unsigned default:0', created_by: 'integer unsigned nullable', updated_by: 'integer unsigned nullable' }
    Models\AdvertisementLog: { tenant_id: 'integer unsigned', advertisement_id: 'integer unsigned', type: 'boolean unsigned default:0', guest_id: 'integer unsigned nullable', user_agent: 'string nullable', ip: 'string:45 nullable', mac: 'string:17 nullable' }
```

It goes on for other 60 models. We keep models in `app/Models` btw.

**Comment by jasonmccreary** [comment]
Seems good. Thanks for following up.

**Pull request merged**
