### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^9.5.10`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/laravel-shift/blueprint/pull/596/commits/3a4fb9ba2d1346594a0965e8325252c23fe60394?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/blueprint.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravel-shift/blueprint": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by pxpm** [comment]
Hey @jasonmccreary hope to find you well. 

Just to let you know that we tested the L10 branch against our use case and everything seems to be working, at least the bits we use. 

I also ran the tests on our setup PHP 8.2, L10 and everything came back green:
image

Let me know if I can help you with something else to move this PR foward. 

Cheers

**Comment by sajaddp** [comment]
Can you please check this? @jasonmccreary

**Comment by jasonmccreary** [comment]
This is far from complete to take advantage of all Laravel 10 has to offer. So it'll probably be another week before it is merged.

In the meantime, I have adjusted the constraints on `master` to allow installing Blueprint with a Laravel 10 application. However, until this is merged, Blueprint will not generate code with the latest Laravel conventions.

**Pull request closed without merging**
