### PR TITLE
Add support for generating indexes (including composite indexes) in migrations

### PR DESCRIPTION
**Pull request by DennisOng**
For: https://github.com/laravel-shift/blueprint/issues/271

Unfortunately, the syntax proposed here will require using array within the YAML draft file, which would be incompatible with: https://github.com/laravel-shift/blueprint/pull/260 

Opening this for a discussion, not sure what would be the best way forward to be honest

### CODE REVIEW

**Comment by DennisOng** [comment]
Ah sorry just saw the other PR from @nathane on this same thing, what a coincidence! 

Feel free to close this off if that works :)

**Comment by jasonmccreary** [comment]
Actually, per the comment I left on that PR, I like your syntax better. Is it possible for you to review that PR and combine any improves (code or test coverage) into this one?

Also, can you update your PR description with the new syntax.

Again, likely something I will change in v2. But the nested array structure is more inline with the current Blueprint syntax than underscores...

**Comment by jasonmccreary** [comment]
Thanks. I have updated this to avoid changing the public method signature of `Blueprint::parse`. Hopefully merging #351 shortly.

**Comment by DennisOng** [comment]
@jasonmccreary Cheers for taking over and making those changes, good idea on limiting the check for array syntaxes, was stuck on the best way forward there.

Sorry for the delayed response to review the initial PR, was having a long overdue `self disconnect --force` weekend :) 

Thanks

**Pull request closed without merging**
