### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/laravel-shift/blueprint/pull/538/commits/6b3ddc1ec74da27da6421ac8c886ae1dee5f02ae?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/blueprint.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravel-shift/blueprint": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by ghostwriter** [comment]
https://github.com/laravel-shift/blueprint/runs/4926506725?check_suite_focus=true#step:12:23

CI is failing because the call to `$this->filesystem->stub('constructor.stub')` is cached here on consecutive calls via the `static $constructor` (#303). https://github.com/laravel-shift/blueprint/blob/d3d33a05dd204fa7c63dbfeac976dbf864dc206b/src/Generators/StatementGenerator.php#L11-L16

the rest of the failing tests should pass after this behavior is corrected.

**Comment by jasonmccreary** [comment]
@ghostwriter, thanks. That wasn't quite it. More that Shift (Rector) deleted/modified the fixture files. 🙃

**Comment by jasonmccreary** [comment]
This is blocked until more packages have support.

**Pull request merged**
