### PR TITLE
Fix duplicate and missing return type declarations

### LINKED ISSUE #432: Duplicated return type declarations
- Laravel Version: 8.28.1
- PHP Version: 8
- Blueprint Version: dev-master as 1.21.0
- Platform: Mac

### Issue:
- Related to PR #404 
- **Model** problem: For each relation the return type declaration is duplicated.
- **Controller** problem: Return type declaration **only** generated for `index`, `create`, `store`, the other resource methods doesn't have a return type.

### draft.yaml:
```yaml
models:
  Term:
    uuid: string unique
    name: json
    description: json nullable
    meta: json nullable
    user_id: id nullable foreign onDelete:null onUpdate:cascade
    team_id: id foreign onDelete:cascade onUpdate:cascade
    published: boolean default:1
    type: string nullable default:booking
    softDeletes
    relationships:
      belongsToMany: Organizer, Event

controllers:
  Term:
    resource
```

Models/Term.php, duplicated return type declarations
```php
//...

/**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function organizers(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(\App\Models\Organizer::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function events(): \Illuminate\Database\Eloquent\Relations\BelongsToMany: \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(\App\Models\Event::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function team(): \Illuminate\Database\Eloquent\Relations\BelongsTo: \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\Models\Team::class);
    }

```

TermController.php, missing return type declarations
```php
<?php
//example index() has return type declaration
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request): \Illuminate\Http\Response
    {
        $terms = Term::all();

        return view('term.index', compact('terms'));
    }

   // create() ok

   // store() ok

   // show() missing statement
    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Term $term
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Term $term)
    {
        return view('term.show', compact('term'));
    }

  // edit() missing declaration

  // update() missing declaration

  // destroy() missing declaration
```

### PR DESCRIPTION
**Pull request by nathane**
resolves #432

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@tanthammar, could you pull this branch and check if it resolves your issue.

**Comment by justin713** [comment]
I was getting the same behavior (duplicated return types on relationships). This branch seems to have resolved this. I also have a bit of #410 happening concurrently but I don't suspect they're related as this branch had no effect.

**Comment by tanthammar** [comment]
Works :) Thank you @nathane

**Comment by jasonmccreary** [comment]
Awesome. Thanks all, I'll get this merged and tagged shortly.

**Pull request merged**
