### PR TITLE
Update ControllerLexer.php

### PR DESCRIPTION
**Pull request by dishereandy**
Proposed fix for checking if resource method is prefixed with API. Solution provided by @nathane .

### CODE REVIEW

**Comment by jasonmccreary** [comment]
This doesn't necessary solve the use case of mixed actions. For example, `api.show, web.store`.

Ideally, this would also ensure there are no `web.` prefixes...

**Comment by dishereandy** [comment]
Yeah, I was too focused on api that I forgot about web.

**Comment by dishereandy** [comment]
From what I can gather, I think a new function for checking the prefixes of each of the controller's methods is needed. I'm not sure but I think right now, it is only checking once for whether the resource is api or web for each controller and sets the `setApiResource` to true which negates everything written behind the first method. Currently if I use `resource: web.index, api.store`, `setApiResource` will be set to false for every method and likewise if I use `resource: api.store, web.index`, it will be set to true for every method.

**Comment by jasonmccreary** [comment]
I agree.

As I've said, ideally this would only consider it an _API resource_ if it were `api` and none of the actions started with `web.`.

You have half of that logic. Just write the other half ;)

**Comment by dishereandy** [comment]
Haha, I know the logic but I don't how to write the code. I'll try though but as I have some projects to do, I don't think I can dedicate a lot of time to this. In the mean time I'll leave the issue and the pull request,  in case somebody  figures out a solution.

**Pull request closed without merging**
