### PR TITLE
php artisan blueprint:new

### PR DESCRIPTION
**Pull request by Wowenko**
This is a WIP for #168.

### CODE REVIEW

**Comment by ProjektGopher** [comment]
I think your it_creates_an_empty_draft_file() test would fully create the file during testing wouldn't it? If we use 

$file = \Mockery::mock(Filesystem::class);
        $file->expects('put')
        ->with('draft.yaml');

It would test it without creating the file

**Comment by ProjektGopher** [comment]
I hadn't realized someone else was working on the same feature I was, but in my PR #184 the blueprint:start command also fills the draft.yaml file with stubs/draft.stub. I couldn't figure out the testing though

**Comment by jasonmccreary** [comment]
@Wowenko thanks for this. I am going to close it though to avoid confusion and mark the issue as "in progress".

Feel free to point @ProjektGopher in the right direction as far as tests. But his implementation seems just slightly farther along.

**Comment by Wowenko** [comment]
No problem I'm here to help an learn.

**Pull request closed without merging**
