### PR TITLE
Add new command to publish stubs

### LINKED ISSUE #528: Stubs/config publish 'improvement'
### Synopsis:
It looks like the current method of publishing the 'stubs' files, is to use ```php artisan vendor:publish --tag=...``` which is usable. I think there may be room for improvement. Similarly it might be useful to complete multiple steps in one line (new, publish stubs, publish config)

### Proposed Syntax:
Use a new command for config publishing, which then simply calls the vendor:publish

```php artisan blueprint:stubs```

The ```blueprint:new``` command could have a couple of flags like so:

```blueprint:new --config```
```blueprint:new --stubs```
```blueprint:new --cs``` (or shorthand)

### Expected Behavior:

1. Specific command for publishing (similar laravel)
2. Streamline 3 steps into 1 step for those wanting to start a new draft file, publish stubs and publish config

### PR DESCRIPTION
**Pull request by benjam-es**
…and add some shortcut flags to the blueprint:new command for streamline publishing - Closes #528

### CODE REVIEW

**Comment by benjam-es** [comment]
Added as a separate commit, the ability to simply hook into Laravel's stub:publish command, incase you wanted to make the decision on that separately.

**Comment by jasonmccreary** [comment]
Any reason the shorthand command options need to be capital? Would rather save the keystrokes. Also, I think you can do a single dash (`-`) for short options too ([ref](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/ModelMakeCommand.php#L204))

**Comment by benjam-es** [comment]
Happy to change if preferred? 

Just followed the convention in Laravel docs, but I agree, the idea is for the minimal amount of keystrokes.

**Comment by jasonmccreary** [comment]
@benjam-es, do you know if you have to type `--c` or can it just be `-c`?

**Comment by benjam-es** [comment]
the shorthand allow -c, -s and -cs

**Pull request merged**
