### PR TITLE
Add ability to generate API resource controllers

### PR DESCRIPTION
**Pull request by tectiv3**
Hi!
I've extracted API Resource related changes from my fork into this PR.

Please take a look, does everything makes sense?

Tried to keep unrelated changes to the minimum, had to add prettier config so my editor wouldn't reformat the whole file on every save :)

### CODE REVIEW

**Comment by jasonmccreary** [comment]
This code looks good, but again, with no tests, I can't merge such a large feature.

**Comment by jasonmccreary** [comment]
Also, please remove the `.prettier` and `.gitignore` changes. These are for your system and not this project.

**Comment by tectiv3** [comment]
> Also, please remove the `.prettier` and `.gitignore` changes. These are for your system and not this project.

Okay! No problem, thought it might help other contributors.

I’m really not good at writing tests but I’ll try to follow along.

**Comment by jasonmccreary** [comment]
If it were project specific stuff, sure. This project already uses PHP CS and Style CI. So there's no reason to add Prettier. And `.DS_Store` is MacOS specific and should be part of your global ignore anyway.

As far as the tests, it's okay if you don't have full coverage.

Maybe try to add one for the `ResourceStatement` and one for the expected API controller output. You should be able to mimic the existing tests to write those with minimal work. It's mostly set up of the fixtures for the input and expected output.

**Comment by defenestrator** [comment]
> I’m really not good at writing tests but I’ll try to follow along.

I'm happy to help write some tests for this, if you would like. I'm digging this tool and your commit could be very helpful to me.

**Comment by tectiv3** [comment]
> > I’m really not good at writing tests but I’ll try to follow along.
> 
> I'm happy to help write some tests for this, if you would like. I'm digging this tool and your commit could be very helpful to me.

by all means!

**Comment by defenestrator** [comment]
I'm going to work on this today.

**Comment by jasonmccreary** [comment]
@defenestrator no worries. Take a crack at it and I can always clean it up. Maybe a live-stream Friday.

**Comment by jasonmccreary** [comment]
I started working on this earlier. Due to GitHub's limitations for working on a contributors branch directly, I am going to close this and will open a new one with your work + mine.

**Comment by defenestrator** [comment]
Aw shoot, I was going to merge into his fork to update the PR, but the needs of other humans in the world pulled me away. I didn't know there were GitHub limitations that would cause an issue, interesting. I had other priorities, dang it.

**Comment by jasonmccreary** [comment]
No worries. If you have changes you did, you can try to PR them into [the branch I made](https://github.com/laravel-shift/blueprint/tree/tectiv3-api-resources).

**Pull request closed without merging**
