### PR TITLE
Add HasUuids trait when Model has id uuid primary. 

### PR DESCRIPTION
**Pull request by rcrosbourne**
Addresses issue #646

### CODE REVIEW

**Comment by jasonmccreary** [comment]
Thanks for this. While the build is passing, you need to lint the code. You may do so by running `vendor/bin/pint`, then submit your changes.

There are some other refactors I would make, but if you can lint your code, I'll do the rest.

**Comment by rcrosbourne** [comment]
Hey J Mac, 

I ran the linter. The code now conforms to the standard.

**Comment by brocard** [comment]
thanks @rcrosbourne

**Comment by jasonmccreary** [comment]
I cleaned up a few things, but there's more I'd like to fix. The functionality and test is there. So that's good enough to merge. I'll do the rest on master before merging.

**Pull request merged**
