### PR TITLE
Stubs helper

### PR DESCRIPTION
**Pull request by devmsh**
The old stubs reference prevents me from running the test case directly in PHPStorm alone because it references a relative directory.

I add a new helper to `TestCase` to make it easier to reference stubs in test cases and modify the old tests to use it.

### CODE REVIEW

**Comment by spaceemotion** [comment]
I'm curious to know why it's failing for you in PhpStorm as it works with no problems for me.

**Comment by devmsh** [comment]
@spaceemotion try run a single test or class containing a stub reference. 

The current files_get_content will not find the relative path.

**Comment by spaceemotion** [comment]
image

 ¯\\\_(ツ)_/¯

**Comment by jasonmccreary** [comment]
Yes, seems like a PHPStorm configuration issue and not an issue with Blueprint.

Nonetheless the helper is a nice refactor as it centralizes the pathing and communicates a bit better.

However, I'm going to sit on this until the other PRs are merged so it can be updated to ensure we didn't miss any spots.

**Comment by devmsh** [comment]
This is my phpstorm and machine info
```
PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020
macOS 10.15.5
```

And by default, once I try to run a single test it runs the following command with the following error.

```
Testing started at 08:52 ...
/usr/local/Cellar/php/7.4.3/bin/php /Users/devmsh/projects/opensource/blueprint/vendor/phpunit/phpunit/phpunit --configuration /Users/devmsh/projects/opensource/blueprint/phpunit.xml --filter "/(Tests\\Feature\\Generators\\ModelGeneratorTest::output_works_for_pascal_case_definition)( .*)?$/" --test-suffix ModelGeneratorTest.php /Users/devmsh/projects/opensource/blueprint/tests/Feature/Generator --teamcity
PHPUnit 9.2.6 by Sebastian Bergmann and contributors.


ErrorException : file_get_contents(stubs/model.class.stub): failed to open stream: No such file or directory
 /Users/devmsh/projects/opensource/blueprint/tests/Feature/Generator/ModelGeneratorTest.php:103
```

**Comment by devmsh** [comment]
Conflict with `master` fixed

**Pull request merged**
