### PR TITLE
Generate resources and specific API actions

### PR DESCRIPTION
**Pull request by jasonmccreary**
This pull request contains two new features related to generating [API Resources](https://laravel.com/docs/eloquent-resources). This replaces #75.

**Features:**
1. A new `resource` statement which generates a response based on the definition for either a singular resource, collection, or paginated collection.
2. Generate separate API controller actions using `resource` when defining a `resource: api` controller.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@tectiv3 This contains the rework.

A few changes:

- I removed the addition for `user.all` as I didn't know what it was.
- I'm going to work on the generation of API routes in a separate PR.
- Update the format of the resource statement to match other statements, e.g. `resource: collection:users`, and streamlined the paginate version, e.g. `resource: paginate:users`.

**Comment by tectiv3** [comment]
from https://github.com/laravel-shift/blueprint/issues/73#issuecomment-602351766
>In this case query: user.all is in play, which is also a shorthand to get all models for current user.
>        $subscriptions = auth()->user()->subscriptions();

**Comment by narwy** [comment]
@jasonmccreary When will these be merged in + released?

**Comment by jasonmccreary** [comment]
@narwy, probably tomorrow. Was waiting on some feedback from everyone in hopes they tested it.

**Pull request merged**
