### PR TITLE
Optimize unsigned columns

### LINKED ISSUE #5: Optimize column datatypes
When defining models it would be good to _optimize_ any column data types and modifiers.

For example, the definition `column: integer unsigned` currently generates `$table->integer('column')->unsigned()`, but could be optimized to generate `$table->unsignedInteger('column')`.

Additional optimizations can be inferred from the [list of available data types](https://laravel.com/docs/5.8/migrations#creating-columns).

### PR DESCRIPTION
**Pull request by willvincent**
Any unsignable datatype that has the unsigned modifier specified will be optimized to it's `unsigned[type]` corresponding datatype.

ie: 
```
foo: integer unsigned
```

Becomes:
```
$table->unsignedInteger('foo');
```

And so forth.

Closes #5

### CODE REVIEW

**Comment by jasonmccreary** [comment]
Very nice. Are there any others you think, beyond `unsigned`?

**Comment by willvincent** [comment]
Guess there are a couple nullable too.. nothing else jumps out at me. Let me get those added though

**Comment by willvincent** [comment]
Omitted `nullableTimestamps()` as that's the same as `timestamps()` and arguable less optimal :)

**Comment by willvincent** [comment]
Good call.. `Str::StartsWith` is more readable

**Comment by jasonmccreary** [comment]
Yeah. I'll likely optimize the `continue` as well, but this is a great start.

**Pull request merged**
