### PR TITLE
feat: support nullable columns in model factories

### PR DESCRIPTION
**Pull request by nathane**
Use Faker's `optional()` modifier for `nullable` columns.

#78

### CODE REVIEW

**Comment by jasonmccreary** [comment]
I like how this communicates its an _optional` (aka nullable) piece of data. But since this doesn't ensure the data will always be `null`, I'm not sure if it's worth merging...

**Comment by nathane** [comment]
> But since this doesn't ensure the data will always be`null`, 

```
// optional() accepts a weight argument to specify the probability of receiving the default value.
// 0 will always return the default value; 1 will always return the provider. Default weight is 0.5 (50% chance).
$faker->optional($weight = 0.1)->randomDigit; // 90% chance of NULL
$faker->optional($weight = 0.9)->randomDigit; // 10% chance of NULL

// optional() accepts a default argument to specify the default value to return.
// Defaults to NULL.
$faker->optional($weight = 0.5, $default = false)->randomDigit; // 50% chance of FALSE
$faker->optional($weight = 0.9, $default = 'abc')->word; // 10% chance of 'abc'](url)

```

**Comment by jasonmccreary** [comment]
I see. I read the docs too quickly. 

I like how this communicates the `null` value, but quickly allows a developer to remove the `optional` prefix if they want to fake the data.

I'm not sure if this would be considered a "breaking change". It takes a bit of a different meaning with Blueprint as this generates code. Meaning the code it already generated would not be affected. However, it is different behavior moving forward...

Going to wait a bit on this...

**Comment by jasonmccreary** [comment]
Still can't decide on this, so I think it means "close it for now".

While I may not always agree with it, I think faking nullable columns in the default factory definition is the most _helpful_ approach.

**Pull request closed without merging**
