### PR TITLE
Added Polymorphic Relationship

### PR DESCRIPTION
**Pull request by RahulDey12**
Fix against #199
New Syntax Should Be Like

```
Post:
    title: string:400
    published_at: timestamp nullable
    relationships:
      morphMany: Comment

  Comment:
    title: string
    relationships:
      morphTo: null
```

### CODE REVIEW

**Comment by jasonmccreary** [comment]
I don't understand the `morphTo: null` in your example. Why would you define something this way?

Also, I am glad to help with the tests, but what is the expected output for each of the generated _morph_ relationship methods?

**Comment by RahulDey12** [comment]
`morphTo: null` Because of no class required for  `morphTo`

**Comment by jasonmccreary** [comment]
Again, examples of the expected would be appreciated or links to the docs so I can determine what code this generates so it can be properly tested.

Otherwise, I will not be able to merge.

**Comment by RahulDey12** [comment]
image
image
image

**Comment by RahulDey12** [comment]
also, you can check by installing my forked repo

**Comment by jasonmccreary** [comment]
Alright, I'll take a look at the Laravel docs and rework this accordingly.

In the future, I would encourage you to include the related information in your pull requests to make it easier on the maintainers of the open source project to understand and verify your changes. This will also give your contribution a better chance at being accepted.

**Comment by RahulDey12** [comment]
Is it worked ?

**Pull request closed without merging**
