### PR TITLE
Support model reference in validate statement to validate all columns

### LINKED ISSUE #172: Support model reference in `validate` statement to validate all columns
As mentioned in #171 

Given the following contents of `draft.yaml`:
```yaml
models:
  Certificate:
    name: string
    reference: string
    document: string
    expiry_date: date
    remarks: nullable text

controllers:
  Certificate:
    resource: api
```

Where we use a `resource: api` to generate an REST API Controller.

Running `blueprint:build` will yield:
```sh
- database/migrations/2020_05_02_092122_create_certificates_table.php
- app/Certificate.php
- database/factories/CertificateFactory.php
- app/Http/Controllers/CertificateController.php
- app/Http/Requests/CertificateStoreRequest.php
- app/Http/Requests/CertificateUpdateRequest.php
- app/Http/Resources/CertificateCollection.php
- app/Http/Resources/Certificate.php
- tests/Feature/Http/Controllers/CertificateControllerTest.php
```

If we inspect the StoreRequest and UpdateRequest, and particularly the `rules()` within, we will find the following bogus rule:

```php
    public function rules()
    {
        return [
            'certificate' => 'required',
        ];
    }
```

The expectation here is that the rules should match/correspond with the model's definition.

The generated tests also fail because of this:

```sh
❯ phpunit                                                                                                                                                                                                                         28%
PHPUnit 8.5.4 by Sebastian Bergmann and contributors.

..R.FR.R.                                                           9 / 9 (100%)

Time: 326 ms, Memory: 30.00 MB

There was 1 failure:

1) Tests\Feature\Http\Controllers\CertificateControllerTest::store_saves
Failed asserting that actual size 0 matches expected size 1.

/Users/joostjacobs/Code/blueprint/tests/Feature/Http/Controllers/CertificateControllerTest.php:55
```

### PR DESCRIPTION
**Pull request by Pr3d4dor**
I think this solution can be improved.

---
Closes #172

### CODE REVIEW

**Comment by jasonmccreary** [comment]
I think this looks like a good start. What were your concerns or improvements?

Much better commits this time too. 😉

**Comment by Pr3d4dor** [comment]
I think it can be refatored using Laravel Collection to improve code readability.

**Comment by jasonmccreary** [comment]
I see. Yeah. That's the entire codebase. 😅

**Comment by Pr3d4dor** [comment]
I will try to refactor using Laravel Collection, but the upcoming week will be a little busy, so maybe I will not have time. But if you think this looks good and worth to merge, maybe you can refactor later then.

**Comment by jasonmccreary** [comment]
No worries. I'll take a stab later in the week.

Thanks again.

**Pull request merged**
