### PR TITLE
Add Morphs and uuidMorphs php annotation

### LINKED ISSUE #422: Morphs php annotation incorrect
* Laravel Version: 8.24.0
* PHP Version: 8.0
* Blueprint Version: 1.20.2
* Platform: Mac

In yaml
```yaml
obj: morphs
```

Generated annotation in Model:
```php
/**
 * @property string $obj
 */
```

Expected:
```php
/**
 * @property int $obj_id
 * @property string $obj_type
 */
```

Didn't test morphsUuid...

### PR DESCRIPTION
**Pull request by tanthammar**
fixes #422 
Don't know if you prefer a switch statement or elseif

### CODE REVIEW

**Comment by jasonmccreary** [comment]
`if`/`else` is fine.

Can you back this up with a test? There should be an example fixture already you can add the proper syntax to do demonstrate is generating your new DocBlocks.

**Comment by tanthammar** [comment]
@jasonmccreary 

I don't know the "best practice" for naming the `id` column on the `uuidMorphs` column type.
I've set it to `name._id`, should it be `name.uuid`?

I'll add a test.

**Comment by jasonmccreary** [comment]
@tanthammar I'm not sure what you're asking. Go ahead with the test and I'll review/tweak whatever you send.

**Comment by nathane** [comment]
@tanthammar The [`uuidMorphs()`](https://laravel.com/docs/8.x/migrations#column-method-uuidMorphs) method adds a `{column}_id` `CHAR(36)` equivalent column and a `{column}_type` `VARCHAR` equivalent column.

There is also the [`nullableUuidMorphs()`](https://laravel.com/docs/8.x/migrations#column-method-nullableUuidMorphs) similar to the `uuidMorphs` method; however, the columns that are created will be "nullable". (if you'd like to attempt to add this as well)

**Pull request closed without merging**
