### PR TITLE
Feature: publish stubs

### PR DESCRIPTION
**Pull request by bingtsingw**
### What it does:
#164 
- when running `php artisan vendor:publish --tag blueprint-stubs`, it will copy default stubs to project's `stubs/blueprint` folder.
- If project level stub exists, blueprint generator will use user stubs.

### What it NOT does:
- use laravel's own stubs which is located in project's `stubs` folder. I think this approach it's just fine :)

### What left off:
- [x] rename/move stubs files
- [x] maybe rename some placeholder
These are for elegant purpose, because once this feature rolled out, changing them will affect end user.

### CODE REVIEW

**Comment by bingtsingw** [comment]
I have done renaming stub files, see https://github.com/bingtsingw/blueprint/commit/fd6352ddb8461b0885db5aa7f8fd31e09e8baecf, I can add it to this pr if you think it's proper.

**Comment by jasonmccreary** [comment]
What placeholders would you rename?

**Comment by bingtsingw** [comment]
Hi, I already have everything done, just not sure if you have anything to check and add, so I left rename open for discussion, If you think everything is OK, just ignore it and merge.

There is one thing I'll point out:
Blueprint's form request stub is named `form-request.stub`, Lavavel's is named `request.stub`, I think blueprint's name is just fine, so I do not change it. What do you think?

**Comment by jasonmccreary** [comment]
Yes. Let's go ahead and rename the _form request_ stub.

**Comment by bingtsingw** [comment]
I renamed `form-request.stub` to `request.stub` and also renamed `model.method-comment.stub` to `model.method.comment.stub` for this naming convention.

**Comment by jasonmccreary** [comment]
Thanks. I'll merge this shortly, but wait to tag it until Thursday's live-stream. I'd like to test it locally and compare it to Laravel's `publish` command to see if there are any additional opportunities to align these more closely.

Until then, feel free to point to `dev-master` to try out these changes.

**Pull request merged**
