### PR TITLE
implementing nullable email rule

### PR DESCRIPTION
**Pull request by Treggats**
Implementing part of issue #17 

Added a test for nullable email rule.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
Thanks for sending this in. A few quick things preventing me from merging.

- Does it make sense for a rule to be both `required` and `nullable`? Or is it one or the other...
- There is no data type of `email`. The type would be `string` and the name of the column would be `email` or `email_address`. For clarity, the data types are any of the [migration column types](https://laravel.com/docs/5.8/migrations#creating-columns).
- Ideally, if `email` was used, it would ignore the `dataType` check. Preventing a rule from being `required|string|email`.

As you can tell, this isn't so easy. A lot of work involved for even the most basic field. So I welcome the help.

If you want to make these changes, great. Otherwise, I'll expand on this next week.

**Comment by Treggats** [comment]
Just a short note, I'm going to work on this this weekend.

**Comment by jasonmccreary** [comment]
No worries.

After closer reading, I think we'll disregard `nullable` for v1. If the developer has chosen to define a field to validate, the base rule should always be `required`.

**Comment by Treggats** [comment]
@jasonmccreary I removed the nullable rule check, left a todo for post v1

I check if a email field is present by the name of the column and apply the rule.
The other string rules were moved to a private method with a guard clause if the email rule was applied. If that's the case the other string rules are ignored.

**Comment by jasonmccreary** [comment]
Awesome. Looks like someone opened https://github.com/laravel-shift/blueprint/pull/19.

So I'll likely take the best of both PRs to mark this issue complete.

I think the last remaining areas might be `unique` and _relationship_ validations using `exists`. If you feel like tackling that that, great. Otherwise, I'll live-stream it this week.

**Comment by jasonmccreary** [comment]
#19 crushed the tasks. So I'm going to close this one and pull what's needed into it.

**Pull request closed without merging**
