### PR TITLE
Add PHPDoc for model relationships

### PR DESCRIPTION
**Pull request by amir9480**
Hello.

I added PHPDoc with return type to model relationships.
It can help code editor provide autocomplete.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@amir9480, why did you close this? Seems like a good addition. However, I would like to make it conditional based on the `generate_phpdocs` config option...

**Comment by amir9480** [comment]
@jasonmccreary Sorry.
I struggling with unit tests on my machine and can not run PHPUnit tests locally because of some errors like this.
```
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_4::put
```

I want to make sure unit tests pass first.

**Comment by amir9480** [comment]
@jasonmccreary If you have any similar experience with the exception or have any clue why this happening I appreciate it if you let me know.
I still didn't find why this happens.

**Comment by jasonmccreary** [comment]
@amir9480, you'll likely need to `expect` the call you added to get the new stub. Otherwise, the mocked `file` property will throw this exception.

**Comment by amir9480** [comment]
For anyone who comes from the future.

If you using Windows and also docker environment for tests make sure your git config `core.autocrlf` is false. (Mine was true).
Also, make sure your IDE doesn't convert LF to CRLF automatically.
This takes about 4 hours for me to find out 😅.

**Pull request closed without merging**
