### PR TITLE
Support doctrine/dbal ^3.0

### PR DESCRIPTION
**Pull request by candro**

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@candro, what is the purpose of this?

**Comment by keenminded** [comment]
@candro and @jasonmccreary, I too had an issue with the composer when attempting to install the blueprint package on a project with barryvdh/laravel-ide-helper already installed:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-shift/blueprint[v1.20.0, ..., v1.20.1] require doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.12.x-dev] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires laravel-shift/blueprint ^1.20 -> satisfiable by laravel-shift/blueprint[v1.20.0, v1.20.1].
```

'composer why doctrine/dbal' helped identify the laravel-ide-helper as another package using doctrine/dbal. My quick solution was to uninstall the ide helper package, install blueprint and then reinstall the ide-helper.

Hope this helps!

**Comment by jasonmccreary** [comment]
@keenminded it does. Thanks. I have merged this into master. If you could retry by constraining your Blueprint dependency to `dev-master` and let me know if it is resolved. Then I'll tag a patch release.

**Comment by keenminded** [comment]
@jasonmccreary just installed from dev-master and it worked. Thank you.

**Pull request merged**
